name: Build AUR Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Sy --noconfirm base-devel git sudo icu
      
      - name: Create build user and grant permissions
        run: |
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /build
          chown -R builduser:builduser /build
      
      - name: Install required versions of Node.js and npm
        run: |
          pacman -Sy --noconfirm nodejs-lts-iron npm
      
      - name: Clone and build AUR package
        run: |
          sudo -u builduser bash -c "
          cd /build
          git clone https://aur.archlinux.org/nody-greeter.git aur-package
          cd aur-package
          makepkg -s --noconfirm --needed
          "
      
      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: /build/aur-package/*.pkg.tar.zst
